###################################################################
# CC LIBERTY SERVER MIGRATION PROPERTIES
# For migrating CC Liberty servers to the current version
###################################################################

###################################################################
# File section
###################################################################
SERVER_INSTALL_DIR=/usr/lpp/IBM/uko/v3r1/cc
SERVER_DIRECTORY=/etc/liberty/CCSERV
SERVER_FILE_SYSTEM_HLQ=CC.ZFS
SERVER_STC_NAME=CCSERV

###################################################################
# Server parameters
###################################################################
SERVER_STC_USER=CCSU
SERVER_STC_GROUP=CCSG
WLP_UNAUTHENTICATED_USER=CCUU
WLP_UNAUTHENTICATED_GROUP=CCUG
GENERIC_CLIENT_USER=CCGU
GENERIC_CLIENT_GROUP=CCGG

###################################################################
# Network properties
###################################################################
SERVER_PORT_NOTLS=-1
SERVER_PORT_TLS=443
ENABLE_MTLS_VIA_HTTPS_PORT=true

###################################################################
# Other server-related properties
###################################################################
SERVER_HOSTNAME=
SAF_PROFILE_PREFIX=EKMFWEB
WLP_ANGEL_NAME=CCANG

###################################################################
# Feature flags
###################################################################
MSDKE_SUPPORT_REQUIRED=false
CRYPTO_CONNECT_SUPPORT_REQUIRED=true
CAT_SUPPORT_REQUIRED=false

###################################################################
# MSDKE database parameters (if MSDKE_SUPPORT_REQUIRED=true)
###################################################################
DB_CURRENT_SCHEMA=CCDB
DB_HLQ=SYS2.DB2.V13
DB_JCC_SSID=DL3N
DB_LOCATION=DSNV133N

###################################################################
# Other
###################################################################
TEMP_DIR=/tmp

###################################################################
# Variables to be migrated (version-specific)
###################################################################
# These parameters are only needed when migrating from specific older versions

# migrating from V3.1.0.9 or older
# Verify the Java dependency of your CC version
JAVA_HOME=/java/java17_64

# migrating from V3.1.0.1 or older  
# Db2 lib path parameter, required for server.env
DB_LIBPATH=/db2/db2v13/jdbc/lib
# Db2 class path parameter, required for server.env
DB_CLASSPATH=/db2/db2v13/jdbc/classes

# migrating from V3.1.0.8 or older
# Hostname parameter was reintroduced
# SERVER_HOSTNAME=
